version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@trpc/server"
      - dependency-name: "@trpc/client"
      - dependency-name: "@trpc/react-query"
