packages:
  - apps/marketing
  - apps/saas
  - packages/api
  - packages/auth/server/base
  - packages/auth/server/nextauth
  - packages/auth/server/supabase
  - packages/auth/client/base
  - packages/auth/client/nextauth
  - packages/auth/client/supabase
  - packages/config/eslint-config-custom
  - packages/config/tailwind-config
  - packages/config/tsconfig
  - packages/database/base
  - packages/database/prisma
  - packages/billing/base
  - packages/billing/lemonsqueezy
  - packages/billing/stripe
  - packages/mail/base
  - packages/mail/plunk
  - packages/mail/nodemailer
  - packages/common
  - packages/ui
