packages:
  - apps/web
  - packages/backend/api
  - packages/backend/auth
  - packages/backend/billing/base
  - packages/backend/billing/lemonsqueezy
  - packages/backend/database
  - packages/backend/mail
  - packages/config/eslint-config-custom
  - packages/config/tsconfig
  - packages/frontend/shared/api
  - packages/frontend/shared/tailwind
  - packages/frontend/web/common
  - packages/frontend/web/ui
  - packages/frontend/web/auth
