name: e2e

on:
  - push
  - pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install cypress
        uses: cypress-io/github-action@v5
        with:
          runTests: false
      - run: pnpm build
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: apps/web
          start: pnpm start
          wait-on: "http://localhost:3000"
